drop policy "managers_manage_certification_catalog" on public.certification_catalog;
drop policy "managers_manage_brand_requirements" on public.brand_requirements;
drop policy "managers_manage_technician_certifications" on public.technician_certifications;

create policy "managers_insert_certification_catalog" on public.certification_catalog for insert to authenticated with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_update_certification_catalog" on public.certification_catalog for update to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager'))) with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_delete_certification_catalog" on public.certification_catalog for delete to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));

create policy "managers_insert_brand_requirements" on public.brand_requirements for insert to authenticated with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_update_brand_requirements" on public.brand_requirements for update to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager'))) with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_delete_brand_requirements" on public.brand_requirements for delete to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));

create policy "managers_insert_technician_certifications" on public.technician_certifications for insert to authenticated with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_update_technician_certifications" on public.technician_certifications for update to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager'))) with check (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
create policy "managers_delete_technician_certifications" on public.technician_certifications for delete to authenticated using (exists (select 1 from public.user_profiles profile where profile.id = (select auth.uid()) and profile.status = 'active' and profile.role in ('admin', 'brand_manager')));
